language: bash
dist: xenial
addons:
  apt:
    update: true
    packages:
    - pandoc
script:
- pandoc --version
- "./build.sh"
deploy:
  provider: releases
  api_key:
    secure: KemuEexsiUgulkAfrNXPRShjzwi31QFC2VtFiD/jbpNNwoYj2bNWylmzwGXxrJ/M8j77ixuJO1qLzkPgAezQOLkBZHQPZW7FKXctLKkFZqobzjSjMDoW3FSbPiPpURE2IbmLGk/y7Oq81R66I9/2Y5MRIygibmr3kngWBVbqLcz8F73OaqL1vqIxqn6wEgROn5+I2TM7EuE4fbdl94FZkUms4dtwaXa4v+hMJJwYrMXTjtfFGbz4Mk+xRrp0cPD8bx+IDyqiEN0BWU/3LhQmiOWXmECHQ36+2oDe8yIlqEz72U5CgTMCstTpotXTt3CwnJWCPgSi+y0hDi69jdU8CYebOTjsQYTXWDLdSMaX2LHtUZExOJ4YmNUeNbxTnVlTurxTroqjc4dT/DRsbXL/B43Emo7NW5jk/I3ixpEsdcKfmjr4+b5yJGYwF/abm8QesWCAQSCKIxa7v24k/xucTtsYJU/3lKi1OQtIG7nFGYXafrRp8mH1LBvmn9o6ebBxjcYdLAzBxGflHVk5BC9Ina5ZW/nxTwvBDB46/WPL1STg4qpXcHvV9RiYJQZZOJN6TV1GmhLlqtuhIsuO/wt5aKsmTwRRHtV7iYk4wiNaehphtpHaAmridUx2ptr47Wc/36tnfdgWp3L7BcozzTOk45RqmakjdK1CSth1bmzBgLk=
  file:
    - localize-the-docs.html
  skip_cleanup: true
  on:
    repo: apaluya/localize-the-docs
    tags: true
